# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: 15b8a8040af0fe31fc46da4867ab6488
  secret_key: 492ddee03156bcecd8f57c6f44de3ca9
  canvas_page_name:
  callback_url: http://servicedev1.net/
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:


test:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

production:
  api_key: be437507fb7096f8faf2d9d9cda1607f
  secret_key: eaa491647bbea73cedf613c325299807
  canvas_page_name:
  callback_url: http://www.welltreat.us/
  set_asset_host_to_callback_url: true
  tunnel:

